version: "3"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672
  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/urs/src
  #   environment:
  #     - CLOUDAMQP_URL=amqp://rabbitmq_server:5672
  #     - REDIS_URL=redis://redis:6379/0
  #   depends_on:
  #     - rabbitmq_server 
  #

